### PR TITLE
review request

### PR DESCRIPTION
**Pull request by bobb-Rob**
### Summary

- Updated the .gitignore file to include node_modules folder
- edited the style.css file in the format that linter report recommended

### CODE REVIEW

**Review by AnselemOdims — CHANGES_REQUESTED** [review]
### Hi @bobb-Rob , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [x] Please ensure that your pull request summary is descriptive. It should describe the newly introduced changes in a branch or milestone
- [x] I also noticed from your previous merges that the `node_modules` folder is not included in the `.gitignore` file. Kindly include it as it will help prevent the push of unnecessary files and dependencies to remote.
- [x] Please ensure that you do not merge any pull request without getting approval to do so. If a change is requested then you will use that same branch and pull request to request for another review.

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by bobb-Rob** [comment]
- Updated the gigignore file to include node_modules folder
- cleared all lint errors

**Comment by bobb-Rob** [comment]
Please highlight specifics so I can get them sorted out all at once.

**Comment by bobb-Rob** [comment]
@AnselemOdims Please what specific changes is required?

**Review by roshan-bajgain — APPROVED** [review]
# Approved 👏 

Hi @bobb-Rob , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Pull request merged**
